USE u3119786_statement_db;

-- Create tables
CREATE TABLE Messengers (
    IdMessenger INT AUTO_INCREMENT PRIMARY KEY,
    Messenger VARCHAR(100) NOT NULL
);

CREATE TABLE FeedbackForm (
    IdFeedback INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(12) NOT NULL,
    MessengerId INT NOT NULL,
    Topic VARCHAR(255) NOT NULL,
    Message TEXT NOT NULL,
    PrivacyCheckbox BOOLEAN NOT NULL,
    SentAt datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (MessengerId) REFERENCES Messengers(IdMessenger) ON DELETE CASCADE
);

CREATE TABLE TgChats (
    IdTgChat INT AUTO_INCREMENT PRIMARY KEY,
    ChatId BIGINT NOT NULL UNIQUE,
    ChatTitle VARCHAR(255) DEFAULT NULL,
    ChatIdAddedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LastMessageSuccessAt DATETIME DEFAULT NULL,
    ErrorCount INT DEFAULT 0
);

CREATE TABLE UserRoles (
    IdUserRole INT AUTO_INCREMENT PRIMARY KEY,
    UserRole VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Users (
    IdUser INT AUTO_INCREMENT PRIMARY KEY,
    UserRoleId INT NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    Token VARCHAR(255) UNIQUE DEFAULT NULL,
    `Name` VARCHAR(100) DEFAULT NULL,
    UserCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastLoginAt DATETIME DEFAULT NULL,
    PasswordUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserRoleId) REFERENCES UserRoles(IdUserRole) ON DELETE CASCADE
);

CREATE TABLE Posts (
    IdPost INT AUTO_INCREMENT PRIMARY KEY,
    CreatedBy INT DEFAULT NULL,
    UpdatedBy INT DEFAULT NULL,
    CanonicalUrl VARCHAR(255) NOT NULL,
    RelativeUrl VARCHAR(255) NOT NULL UNIQUE,
    MediaFolderName VARCHAR(255) NOT NULL,
    PostCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    PostUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsPublished BOOLEAN DEFAULT FALSE,
    PublishedAt DATETIME DEFAULT NULL,
    IsSoftDeleted BOOLEAN DEFAULT FALSE,
    SoftDeletedAt DATETIME DEFAULT NULL,
    BrowserTitle VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Title TEXT NOT NULL,
    Subtitle TEXT NOT NULL,
    Article TEXT NOT NULL,
    Conclusion TEXT NOT NULL,
    FirstImageName VARCHAR(255) NOT NULL,
    SecondImageName VARCHAR(255) NOT NULL,
    ThirdImageName VARCHAR(255) NOT NULL,
    FourthImageName VARCHAR(255) NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES Users(IdUser) ON DELETE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(IdUser) ON DELETE CASCADE
);

CREATE TABLE Notifications (
    IdNotification INT AUTO_INCREMENT PRIMARY KEY,
    CreatedBy INT NOT NULL,
    UpdatedBy INT NOT NULL,
    LastUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Text TEXT NOT NULL,
    ImageName VARCHAR(255) NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES Users(IdUser) ON DELETE CASCADE,
    FOREIGN KEY (UpdatedBy) REFERENCES Users(IdUser) ON DELETE CASCADE
);

-- Insert data into tables
INSERT INTO
    Messengers (Messenger)
VALUES
    ("Telegram");

INSERT INTO
    Messengers (Messenger)
VALUES
    ("WhatsApp");

INSERT INTO
    UserRoles (UserRole)
VALUES
    ("Developer");